services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: Frontend-React.js
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    command: npm start
    networks:
      - frontend
networks:
  frontend:
